# Generated by Django 5.2.4 on 2025-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='header/')),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('last', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Logo',
        ),
        migrations.DeleteModel(
            name='MainPage',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='last',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='main',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='phone',
        ),
    ]
