# Generated by Django 5.2.4 on 2025-07-17 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contactnumbers_header_delete_logo_delete_mainpage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdvantageMenu',
            new_name='Advantages',
        ),
        migrations.RenameModel(
            old_name='Advantage',
            new_name='CertificateTitle',
        ),
        migrations.DeleteModel(
            name='CatalogCategory',
        ),
        migrations.RemoveField(
            model_name='header',
            name='last',
        ),
        migrations.RemoveField(
            model_name='header',
            name='text',
        ),
        migrations.RemoveField(
            model_name='products',
            name='last',
        ),
        migrations.AddField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.catalog'),
            preserve_default=False,
        ),
    ]
