# Generated by Django 5.2.4 on 2025-07-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_advantagemenu_advantages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='NewsTitle',
        ),
        migrations.AddField(
            model_name='header',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
