# Generated by Django 5.2.1 on 2025-07-17 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_social_delete_newstitle_header_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='blog.categorytitle'),
        ),
        migrations.AddField(
            model_name='certification',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.certificatetitle'),
        ),
        migrations.AddField(
            model_name='clients',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='blog.clientstitle'),
        ),
        migrations.AddField(
            model_name='contactnumbers',
            name='contact_us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='blog.contactus'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='social',
            name='contact_us',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social', to='blog.contactus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='blog.catalog'),
        ),
    ]
